### ISSUE TITLE
Select: add onBlur support and maintain focus

### ISSUE THREAD

**Issue by DanEastBentley** [iTwin/iTwinUI-react#108]
The Select component in iTwinUI-react does not support an onBlur prop & callback. When the drop-down is opened, the Select component seems to lose focus; the focus indicator is no longer around the button. When an option is chosen, focus does not return to the button.

Can the Select component maintain focus while the drop-down is open?
Can support for an onBlur prop & callback be added?

**Comment by mayank99** [comment]
> _When the drop-down is opened, the Select component seems to lose focus; the focus indicator is no longer around the button._

Moving focus from the select button into the dropdown options is by design, and is consistent with how native select behaves. It is also how other popular libraries seem to do it.

Moreover, our select is built on top of DropdownMenu, which should also have this same behavior ([recommended by W3](https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html)).

> _When an option is chosen, focus does not return to the button._

I don't think this part is true. When an option is selected, the focus does return, but it may not be "visible" if you're using a mouse (which is again [by design](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible))

See gif. I first select an option using my mouse (click indicated in yellow). The menu closes and the button is focused (not visible), which I can verify by pressing Enter to reopen the menu. After that, I use arrow keys to navigate and Enter to select an option. Now you see the focus styling is visible on the button.

![focus](https://user-images.githubusercontent.com/9084735/120516157-0cfb2700-c39d-11eb-8484-5e80fdc879d0.gif)

---

> _Can support for an onBlur prop & callback be added?_

This is something we could look into, yeah. Might add a prop that exposes all generic attributes of an html element.

**Comment by mayank99** [comment]
`onBlur` is now available in 1.16.0 🚀
