### ISSUE TITLE
Table: Disabled rows

### ISSUE THREAD

**Issue by basanta078** [iTwin/iTwinUI-react#125]
#### Feature
Table currently allows all rows to be selectable when passed isSelectable prop
However there is no api to disable selection for some rows that might not be selectable

Similar feature that exists is of making column sortable by passing isSortable for the whole columns
And you can manually disable/enable sorting for individual column

#### Examples
Provide an api to say whether a row is disabled or not
Disabled row can not be selectable
Disabled row should have a different darker visual background to indicate that the row is disabled

**Comment by mayank99** [comment]
Thanks for the issue. We're currently finalizing the disabled styles, which will look like this:
![image](https://user-images.githubusercontent.com/9084735/121429486-fa589300-c944-11eb-978c-388bf974d7d5.png)
![image](https://user-images.githubusercontent.com/9084735/121429775-4572a600-c945-11eb-9462-5ff9bb3a7e39.png)

Since it's part of a bigger refactor, it might be a while before it's available in react.

**Comment by mayank99** [comment]
This is now available in 1.1.0 🎉
