### ISSUE TITLE
Table: row virtualization

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI-react#157]
#### Feature

In absence of a paginator, it would be nice to have virtualization (only rendering rows that are "visible" in the viewport) for performance reasons.

#### Examples

See this react-window example: https://codesandbox.io/s/3vnx878jk5

**Comment by bentleyvk** [comment]
If I remember correctly `react-window` does not support dynamic row heights because it is done using `position: absolute`. I think `react-window` author didn't know that it can be also done having mocked top and bottom rows and changing their size accordingly to the scroll.
![image](https://user-images.githubusercontent.com/36186912/122871378-94520f80-d337-11eb-89a7-2277abef682d.png)
