### ISSUE TITLE
Projects not using "Open Sans" font-family by default

### ISSUE THREAD

**Issue by Juliakas** [iTwin/iTwinUI-react#182]
#### Environment
- __Package version(s)__: 1.9.0
- __Operating System__: Microsoft Windows 10 Enterprise
- __Browser name and version__: Google Chrome 91.0.4472.124

#### Code Sandbox
Link to a minimal repro: https://codesandbox.io/s/itwinui-react-example-forked-k6wdu?file=/public/index.html

#### Steps to reproduce
1. Go to code sandbox page using chrome (or just directly to https://k6wdu.csb.app/)
2. Inspect `ErrorPage` title.
3. Go to computed tab in devtools and under "Rendered fonts" section notice Arial font being used.

This also applies to storybook. Go to https://itwin.github.io/iTwinUI-react/?path=/story/core-errorpage--forbidden and perform the same steps with this `ErrorPage` component.

#### Actual behavior
Arial font is being used by default.

#### Expected behavior
Open Sans font is expected to be used by default when running react app that imports iTwinUI libraries. Ar at least should be some kind of instruction that fonts need to be imported.

Storybook is not using Open Sans font as well.

**Comment by veekeys** [comment]
Yeah.. Thats a good catch!
@FlyersPh9 have you noticed all our UIs examples(including test htmls) are using arial font, which has a noticeable difference with the standards screenshots?
If we want to update it to use open sans, we will need to download that and also all our visual tests should fail.

**Comment by mayank99** [comment]
@FlyersPh9 Do you know which font styles in the Open Sans we actually use?

https://fonts.google.com/specimen/Open+Sans#standard-styles

Each of these styles is ~60KB (totaling ~600KB) so fetching them all wouldn't be ideal. We could document the ones we need, and give our users an easy way to include them.

**Comment by FlyersPh9** [comment]
The demo pages are loading Open Sans for me, but I also have that font installed locally, so that may be why I haven't encountered this issue.

[This mixin](https://github.com/iTwin/iTwinUI/blob/c68f2508dbaf301255542ae19bbae2f73d824eec/src/style/typography.scss#L37) was created prior to us working on iTwinUI, but I thought this helped with loading webfonts?

I do not know which of those font styles we are using off hand.  Italic is used pretty rarely, so we could probably exclude all of the italics except for Regular Italic.

I have wanted to update the iTwinUI font family fall backs for some time now to use something more like this, so that our [fallback fonts use OS default fonts](https://css-tricks.com/snippets/css/system-font-stack/#method-1-system-fonts-at-the-element-level):
```
"Open Sans", BlinkMacSystemFont, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", sans-serif;
```

**Comment by mayank99** [comment]
If we're considering updating our fonts, we should maybe look into [variable fonts](https://psdtohtml.dev/tutorial/variable-fonts/#:~:text=If%20we%20wanted,gain%20of%2082). But there are only a few [free variable fonts](https://fonts.google.com/?vfonly=true&category=Serif,Sans+Serif) and most of them are ugly.

**Comment by mayank99** [comment]
I think we can close this issue. Loading Open Sans should be left upto the projects. It's a complex process and there are many performance optimizations the project might need to make (such as [using `preload` and `font-display`](https://web.dev/optimize-webfont-loading/)).

At least we've updated our font stack to use system fonts as fallback, so Arial is less likely to be rendered now.

**Comment by veekeys** [comment]
> I think we can close this issue. Loading Open Sans should be left upto the projects. It's not as simple as _"itwinui should load the fonts"_, and there are many performance optimizations the projects might need to make (such as [using `preload` and `font-display`](https://web.dev/optimize-webfont-loading/)).
> 
> At least we've updated our font stack to use system fonts as fallback, so Arial is less likely to be rendered now.

I would suggest adding some info about fonts.. Open-sans is still the first one we recommend, so we could give links to download and code snippet to load it. Just not sure, where such information could be put...

**Comment by mayank99** [comment]
I have added a section about fonts in the [FAQ](https://github.com/iTwin/iTwinUI-react/wiki/FAQ#fonts). Hopefully this clears up some things for you @Juliakas 

---

> [This mixin](https://github.com/iTwin/iTwinUI/blob/c68f2508dbaf301255542ae19bbae2f73d824eec/src/style/typography.scss#L37) was created prior to us working on iTwinUI, but I thought this helped with loading webfonts?

@FlyersPh9 I was reading up on font loading strategies, and it seems that mixin is meant to only be used in the root element (because it expects the user to first load the fonts, and then apply a "font loaded" class on the root element). But we are using it in every component, which negates all benefits. We might want to fix that.

**Comment by Juliakas** [comment]
@mayank99 That looks clear to me.
