### ISSUE TITLE
Select/MenuItem add value props as data-value={value}

### ISSUE THREAD

**Issue by maxime4000** [iTwin/iTwinUI-react#238]
## Feature
Making a big summaries of what is MenuItem, it's an element in a list of elements shown in a dropdown menu. Each MenuItems represent an action or a value that will be send to a function e.g. onClick. From the definition, value is unknown. In reality, value will be a primitive and I wouldn't expect it to be anything else tbh. Value is kept as memory data and is not represent in the html and that is where I see a problem. Select use MenuItem as alternative to option tag. Fine by that as the select tag does not offer much of CSS customization. But here what is missing about the select that old html select offer. **An value attribute.**

## How to satisfy this missing feature ?
Using data-* attributes ! In my case, MenuItem does have the value but is not shown in the html. I'm looking for a way to get the correct item in the select dropdown to make a click action and change the current value. I can use the selector `.iui-select .iui-menu > .iui-menu-item[data-value="SearchValue"]` to find the exact option I want and make a click on the item. All it's need is 2 line added which I can provide in a PR made for Select changes. For the sake of saving my time and yours as this feature request and #225 are alternative to solve the same issue. I will push only one PR.

**Comment by mayank99** [comment]
I think there are multiple problems with internally setting `data-value={value}`.

1. You make a very big assumption that "value will be a primitive". There is a reason we use the `unknown` type. We really do not want anything to do with what's in the value. So, naively assigning that value to a data attribute can potentially break the DOM or unnecessary info there.

2. The user of the component might want to set a different data-value or even remove it. This would be especially needed if `value` is a complex object.

3. Since it's an internal detail, we cannot guarantee that the data-value we set today will remain the same in a future version of iTwinUI-react. Internal implementation changes are not considered breaking changes.

A cleaner solution might be to allow the user to pass any `data-*` attributes, and not automatically setting anything internal.

**Comment by maxime4000** [comment]
1. Yes it's an assumption because 99% of the case it would be a primitive. Object are represent like this [object Object] which is less useful, but does not break. (Don't know if some javascript code can read this object yet as I haven't test everything that wasn't useful to me) The only case that is breaking are when value is a function and at this point, I think you're using the MenuItem/SelectOption value wrongly.
2. Dunno what to said, only function are problematic, Object are less useful (could be skip with conditional if they are useless). Tho, not sure function work in Select anyway. The small testing I made wasn't changing the value of select when it was a function.
3. Well, unless it's remove purposely, I expect that data-value would never change as the value of the Select stay the same in my app. So unless big change in how the component work, I couldn't see why this would stop working later on as data-* is there for custom feature only.

For allowing data-* attributes as props, I think this would add unnecessary complexity/duplication due to all the value needed are already given to the component. I'm open to find a good compromise that would not add excessive overhead, but required additional settings to make data-value work. My PR is about making the minimal changes to get what I want.
