### ISSUE TITLE
Table: status and icons in cells

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI-react#457]
In CSS we have classnames for applying status backgrounds.
![image](https://user-images.githubusercontent.com/9084735/144666233-7606c1a3-5ef1-40e0-a782-bcccaaf0701b.png)

And we also have classnames for aligning icons at the start/end of cell.
![image](https://user-images.githubusercontent.com/9084735/144666314-7a94f78a-08cc-47c5-a79a-9fe00db14ac0.png)

Need a nice way to consume those in React. Currently it requires constructing a manual cell using `cellRenderer` and/or `Cell`. Maybe [`DefaultCell`](https://github.com/iTwin/iTwinUI-react/blob/main/src/core/Table/cells/DefaultCell.tsx) could support status and icon props, or a new similar component with extra props could be added.

**Comment by bentleyvk** [comment]
Wow, our status cells looks so bad in dark theme that at first I didn't even noticed that there were some color. Because in light theme it is clearly visible:
![image](https://user-images.githubusercontent.com/36186912/144866387-b9eff407-e95d-4895-aef1-fbd303a21dd7.png)

**Comment by mayank99** [comment]
It's supposed to be muted like that, though it wouldn't hurt to make it lighter I guess

**Comment by bentleyvk** [comment]
There are also corresponding borders on the row:
![image](https://user-images.githubusercontent.com/36186912/144866540-f6d200c5-234f-4f70-b274-a6029f45c8da.png)

For columns status, yes, we can use `DefaultCell` or we could have some prop in column like function or prop name for the status. For row status I was thinking maybe to reuse `rowProps` that we have: instead of having return type `React.ComponentPropsWithRef<'div'>` it could be `React.ComponentPropsWithRef<'div'> & { status?: 'success' | ... }`
