### ISSUE TITLE
Improvements for iTwin Select/Combobox component

### ISSUE THREAD

**Issue by UnseenMadness** [iTwin/iTwinUI-react#517]
#### Feature
Hello!

We need to have select field with the search functionality in a few places in **Synchro Control**. So iTwin Combobox meets our requirements to replace our component with iTwin but there are some issues that are described further.
We have some Selects with search functionality and possibility of custom rendering for selected fields and menu items (see **Examples**).
All these requirements can be followed by iTwin Select component because it contains **selectedItemRenderer** and **itemRenderer** props to override rendering methods. But Select doesn’t support search functionality.
Search functionality is supported by iTwin Combobox component but it doesn’t support custom rendering on selected field and menu items.
Could supporting of custom renderings be added to Combobox (like in Select component) or could supporting of search functionality be added to Select (like in Combobox component)?

#### Examples
 Selected field rendering:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/61361111/150312193-959ecc5c-a5f7-47cf-abce-2ba104c91b23.png)

Menu items rendering (show tooltips only on truncated text):
![MicrosoftTeams-image](https://user-images.githubusercontent.com/61361111/150312007-5c493337-94d8-4574-b646-c7f7335c8017.png)

**Comment by mayank99** [comment]
Thanks for the issue!

I think we could easily add `itemRenderer` in ComboBox for the MenuItems. That part is fine. 👍

However, it's going to be tough to display in the `<input />` when the menu is collapsed.
![image](https://user-images.githubusercontent.com/9084735/150403080-ca177f98-e105-4257-af54-533305bca89f.png)

@gretanausedaite Since you're already researching (for `Select`) the best/popular practices for displaying custom content overlaying the `<input />`, maybe your findings would help here?

I see that [`downshift-js`](https://www.downshift-js.com/use-combobox) doesn't allow much flexibility for combobox but it does for select. And it does make sense too.

@FlyersPh9 What do you think from a UX perspective? With some hacks, we could force the `<input />` part of ComboBox to show extra things (like icons, sublabels, trailing text, etc), but it would look really weird once the user starts typing because the currently typed text does not immediately correspond to a menu item.

**Comment by UnseenMadness** [comment]
Thanks for your answer!

The Select on our side from the example is implemented in that way: if menu collapsed custom renderer is shown and if it is expanded input is rendered
[image](https://user-images.githubusercontent.com/61361111/150489412-687a7784-469a-458e-a6d4-c57d7cc01ab3.png)

**Comment by FlyersPh9** [comment]
> @FlyersPh9 What do you think from a UX perspective? With some hacks, we could force the `<input />` part of ComboBox to show extra things (like icons, sublabels, trailing text, etc), but it would look really weird once the user starts typing because the currently typed text does not immediately correspond to a menu item.
> 
> That's the reason our [example](https://itwin.github.io/iTwinUI-react/?path=/story/core-combobox--disabled-items) has an inconsistency between how the selected value and the menu item are displayed. ![image](https://user-images.githubusercontent.com/9084735/150404575-b8c448ff-c712-4a62-a1d9-bfd5e4e114e4.png)

I agree with those concerns.  We do not want content shift as things load in.  For example, as the combobox loads in the flag icon or a secondary line of text.  We _could_ leave extra padding to the left to accommodate the flag icon once it's loaded in, but I'm not sure the secondary line of text would work without content shift or without making the select extremely tall.  Placing text right aligned (like the _string_ example above) I think could be doable though, may be tough with really long strings as we'd have to consider truncation.

**Comment by mayank99** [comment]
@UnseenMadness We added a new `itemRenderer` prop to ComboBox in 1.32.0 which should help hopefully. I doubt we're going to offer a way to customize the look of the input field anytime soon.
