### ISSUE TITLE
Checkbox: Clicking the checkbox triggers two click events on the parent element

### ISSUE THREAD

**Issue by roluk** [iTwin/iTwinUI-react#533]
#### Describe the bug (actual behavior)
Whenever user clicks on a `Checkbox` component, two click events are propagated to the parent element. Calling `event.stopPropagation()` inside checkbox's `onClick` event handler only prevents one of the events from reaching the parent.

#### Expected behavior
Whenever user clicks on a `Checkbox` component, one click event is propagated to the parent element. Calling `event.stopPropagation()` inside checkbox's `onClick` event handler prevents the event from bubbling up to the parent.

#### Reproduction
https://stackblitz.com/edit/react-ts-d5bu1c?devtoolsheight=33&file=index.tsx

##### Steps to reproduce
1. Click the checkbox and observe the console output.
1. Comment out `event.stopPropagation()` from line 31.
1. Click the checkbox and observe the console output again.

**Comment by mayank99** [comment]
Hi @roluk 👋 thanks for the issue

It seems the problem is happening because of `label` element wrapping the checkbox. We are considering two options that will help fix this:
- not wrapping with `<label>` when the `label` prop is not passed
- exposing `labelProps` to allow adding event listeners on `<label>`

In the meantime, you can try accessing the label using ref like this:
```tsx
React.useEffect(() => {
  if (checkboxRef.current) {
    checkboxRef.current.parentElement.addEventListener('click', (e) => e.stopPropagation());
  }
}, []);
```

**Comment by mayank99** [comment]
@roluk In 1.32.0 we've refactored our checkbox so that if `label` prop is not passed, then it just renders an `<input>` element. You should be able to remove any workarounds.
