### ISSUE TITLE
Multiple selection and all children selection from parent node Tree

### ISSUE THREAD

**Issue by vishal-shingare** [iTwin/iTwinUI-react#611]
#### Feature
Hi, Is there any plan for multiple selections on Tree, and Also if we select the parent node then all child nodes should also be selected.

#### Examples
I have added my POC with Tree But I miss the following feature to use.
1. Select Multiple nodes from Tree.
2. If we select the parent node then all child nodes should also get selected.
3. Also if we want the checkbox to be shown at the icon place instead all in same column. like this

#### Current:
![image](https://user-images.githubusercontent.com/40196005/160997942-681d8e38-0474-4f5e-9d3e-7d315da035b7.png)

#### Expected
![image](https://user-images.githubusercontent.com/40196005/160997766-34b40e60-1bf7-4286-b978-05ae129eb28a.png)

https://stackblitz.com/edit/react-ts-bm7qcf?file=MyTree.tsx

do you have any future plans for these features or could you please give me any suggestions or any doc so I can refer to get this done.

**Comment by veekeys** [comment]
Hello @vishal-shingare,

All of that is supported in current version of `Tree` component.
Have you checked this story?
https://itwin.github.io/iTwinUI-react/?path=/story/core-tree--full

Our tree is a dumb component, so all the state management is on user. As a result, you can implement what ever you want.
To answer point by point:
1.You are controlling selected nodes at your end. So have a callback on `onSelected` on `TreeNode` and save the list of selected nodes. Then do not forget to get selected value in `getNode`. The story link above has selection state handling, so you can take that as an example.
2. This is same state handling. So whenever `onSelected` is called, you can also get children elements of the selected node and set their state too.
3. Is there a reason you want to do that? Would be interested to hear. I see you already tried using `icon` prop on `TreeNode`, just somehow our css failed to apply spacing in there. It is weird. We can check it up and get back.

Let me know if this information is enough and if you managed to achieve what you wanted.

**Comment by vishal-shingare** [comment]
Thanks, @veekeys I was also thinking in a similar way. let me try and I will let you know if I need something more.
Also, let me know if you get any input or change the checkbox position.

**Comment by veekeys** [comment]
Hey @vishal-shingare 
The spacing issue is fixed in @itwin/itwinui-react@1.35.0, so now you should be able to pass checkbox in icon position.

Let me know if you face any more issues or we can close this.

**Comment by vishal-shingare** [comment]
Hey @veekeys , That's great to add a fix quickly. 
but i stuck on my point number 2.
"If we select the parent node then all child nodes should also get selected". it's difficult to handle the recursive tree states. When we select the parent node. Can you please guide me over or share any example so i can refer.

**Comment by vishal-shingare** [comment]
Hey @veekeys ,

I have found one thing for onSelected callback. it will always give me isSelected param TRUE. even if we click for deselect node.
you can refer to my above POC link. Let me know if you need anything more.
![image](https://user-images.githubusercontent.com/40196005/162288412-14a3e438-7591-4f50-b4a3-f71b80f9a0a6.png)

**Comment by veekeys** [comment]
Hey @vishal-shingare ,

> Hey @veekeys , That's great to add a fix quickly. but i stuck on my point number 2. "If we select the parent node then all child nodes should also get selected". it's difficult to handle the recursive tree states. When we select the parent node. Can you please guide me over or share any example so i can refer.

I have quickly put for you an example, how this could be achieved. You would need to go through the subnodes recursively to add those to your selected state map together with the parent. 
https://codesandbox.io/s/itwinui-react-tree-select-children-bruiyf?file=/src/App.tsx
This is the function, which does that:
![image](https://user-images.githubusercontent.com/81580355/163335141-a7e702b9-b7e8-4989-b140-0f01f778966a.png)

And then you just call it in your `onSelectedNodeChange` handler:
![image](https://user-images.githubusercontent.com/81580355/163335577-f361a986-6024-4ad2-9c61-4c2449a033f9.png)

I guess the only not nice part is handling of `Checkbox` state, which you also need to do semantically correct, so I am stopping propagation to the parent (so when clicking `onSelected` is not triggered) and handling that myself through `Checkbox` native props.

> Hey @veekeys ,
> 
> I have found one thing for onSelected callback. it will always give me isSelected param TRUE. even if we click for deselect node. you can refer to my above POC link. Let me know if you need anything more. ![image](https://user-images.githubusercontent.com/40196005/162288412-14a3e438-7591-4f50-b4a3-f71b80f9a0a6.png)

Yes, because `Tree` component is fully controlled component. That means, that the responsibility of the `Tree` state is on user. I see you are not passing `isSelected` state to the `Tree` on `getNode`. So all you need to do is same as you do already with expansion:
![image](https://user-images.githubusercontent.com/81580355/163335413-3ad26319-67c3-49ca-9584-a96e0375ded5.png)
This example is also shown in storybook, where you can choose `code` tab to see the implementation.
https://itwin.github.io/iTwinUI-react/?path=/story/core-tree--full



Let me know if you face anymore issues or we can close this :)

**Comment by veekeys** [comment]
I am closing this. If anything else pop up, feel free to reopen or create new issue, if its not related.
