### ISSUE TITLE
Table: Select-all deselecting doesn't work when filter is applied

### ISSUE THREAD

**Issue by cfranklyn** [iTwin/iTwinUI-react#616]
#### Describe the bug (actual behavior)
After a filter is applied to a column in a table, the de-select all checkbox does not seem to work.

#### Expected behavior
When a filter is applied, clicking the select all checkbox multiple times should toggle selection and deselection of filtered items. 

#### Reproduction
https://itwin.github.io/iTwinUI-react/?path=/story/core-table--full

##### Steps to reproduce
1. Using the Table/Full iTwinUI-React story, apply filter to a table column to filter out some items (e.g. put "1" in the "Name" column)
2. Click the select all checkbox. All items are selected.
3. Click the select all checkbox again
4. Nothing happens, it does not clear the selection of the items.

**Comment by bentleyvk** [comment]
Hey @cfranklyn, this works as design because it is showing you overall Table selection state - you only see 1 of the 3 rows and only that row is selected -> indeterminate checkbox state because other 2 rows are not selected. We were looking at other libraries and their Tables, some of them are showing checkbox the same as we, some of them are not, so there is no one standard in the community.

**Comment by cfranklyn** [comment]
Understood Vilias. Sorry, I was unaware that was WAD. I have found a workaround in any case.

**Comment by JoeZman** [comment]
Can we open this up for discussion...?  I disagree with the assessment this is a WAD, certainly from a user's perspective, this seems like a bug.  When you click the show/clear all column, it works as expected.  But if a filter is active, select some rows, and click the "clear all" checkbox, it does **nothing**.  This does not seem like a good UI experience.  

Because of this bug, we are forced to implement additional buttons to show and clear all in all out tables.   At the very least, provide a prop to turn this on or off.

Please ping so we can discuss.  As posted earlier in the thread, this is easily reproducible in the sample table components (Zebra Striped Rows for example).
