### ISSUE TITLE
Table: Sort icon is backward

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI-react#641]
The sort icon does not match [iTwin UI specs](http://ux.bentley.com/itwin/patterns/column-sort.html). It should point up when ascending, and down when descending. Currently, it points down when ascending and up when descending.

This can be seen on the current [sortable table story in the docs](https://itwin.github.io/iTwinUI-react/?path=/story/core-table--sortable).

![image](https://user-images.githubusercontent.com/15036346/165816691-f8f66dd9-00fe-4d5a-a5d3-387448802128.png)

**Comment by FlyersPh9** [comment]
We just checked how Windows & macOS does it because we want to align with the industry standard.  Both follow this pattern:
- Arrow points up = A to Z
- Arrow points down = Z to A

That means the standards are correct and our implementation is incorrect.  We'll get a fix in for this.  Good catch @HaveSpacesuit!

**Comment by veekeys** [comment]
This is fixed in [1.37.2 ](https://github.com/iTwin/iTwinUI-react/releases/tag/v1.37.2)!
