### ISSUE TITLE
Select: need a way to disable the `hide` modifier from popper

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI-react#783]
We rely on [popper's `hide` modifier](https://popper.js.org/docs/v2/modifiers/hide/#:~:text=data%2Dpopper%2Dreference%2Dhidden,to%20be%20attached%20to%20nothing.) to hide the popover when the reference element leaves the viewport.

There needs to be a way to disable this modifier either through `popperOptions` or through scoped styling.

Currently if a `className` is passed to `Select`, it gets applied on the select button. If `popoverProps.className` is passed, it gets applied on the menu. There is no way to target the tippy.

This was needed to work around a bug with App UI's modeless dialog. See sandboxes where this bug is found in the select inside the "modeless dialog":
https://www.itwinjs.org/sandboxes/MuthuKalamani/UIControlsInDialogBox
https://www.itwinjs.org/sandboxes/NancyMcCall/Override%20Dialog%20z-index

**Comment by mayank99** [comment]
For more context: the `data-reference-hidden` attribute is being applied incorrectly because the modeless dialog sets `width: 0; height: 0` to hide the backdrop.

https://github.com/iTwin/itwinjs-core/blob/b55e4ecff9423b54cfdfe65da159747438cd0195/ui/core-react/src/core-react/dialog/Dialog.scss#L36-L39

Ideal solution would be to improve the backdrop logic/styles in App UI, but I think it also makes sense for iTwinUI to offer a way to disable this `hide` plugin.

**Comment by rohan-kadkol** [comment]
* I might have understood issue incorrectly, but if this issue is looking for a way to hide a tippy, I think we can call `instance.hide()` [(docs)](https://atomiks.github.io/tippyjs/v6/methods/#show). Here instance is the variable storing the tippy instance.

![image](https://user-images.githubusercontent.com/45748283/186419008-41311381-1387-4774-875e-f6651bae9a92.png)

* We can also hide all the tippys on the page [(docs)](https://atomiks.github.io/tippyjs/v6/methods/#show)

![Screenshot from 2022-08-24 08-33-05](https://user-images.githubusercontent.com/45748283/186419402-6b6da431-0b8d-416e-bfd4-0cf982a53983.png)

* We could also pass a prop to tippy to `hideOnClick` [(docs)](https://atomiks.github.io/tippyjs/v6/methods/#show)

![image](https://user-images.githubusercontent.com/45748283/186420933-c6844b99-42b8-4655-871c-0c7866c9d1f8.png)

* Then there are also props for callbacks for `onHidden` (*"once the tippy has been fully hidden and unmounted from the DOM"*) and `onHide` (*"once the tippy begins to hide"*) [(docs)](https://atomiks.github.io/tippyjs/v6/all-props/#onhidden)

In the `onHide` prop,
> You can optionally return false from this lifecycle to cancel a hide based on a condition.

* We can also use plugins to maintain a state by ourselves [docs](https://atomiks.github.io/tippyjs/v6/plugins/#hideonpopperblur) | [(docs example)](https://atomiks.github.io/tippyjs/v6/plugins/#hideonpopperblur)

> The plugin's function fn returns an object of lifecycle hooks. Plugins are invoked per-instance and the plugin function definition takes the instance as an argument, so you can use private variables to create internal state in the plugin closure.

* Using plugins, we can also hide on our own events, like `hideOnEscape` [docs](https://atomiks.github.io/tippyjs/v6/plugins/#hideonesc)

**Comment by mayank99** [comment]
None of those are really what we need it, except maybe the custom plugins. What I'm talking about is popper's `hide` modifier (I have a link in the issue description) which basically does this: when the reference element (the select button) is scrolled out of the viewport, it hides the popover (the select menu).

And we need a way to disable this feature because it doesn't work in modeless dialog.

**Comment by mayank99** [comment]
One option might be to use [headless tippy](https://github.com/atomiks/tippyjs-react#headless-tippy) and filter out the `data-reference-hidden` attribute based on a new prop. But I think this would require handling some of the other logic ourselves, so we would need to test it.

**Comment by rohan-kadkol** [comment]
From what I have searched, I don't think there is an easy way to disable popper's `hide` mechanism. Playing with the `onHide()` function callback to return false didn't work. As you suggested, one way is to handle the logic of when to add the `data-reference-hidden` attribute ourselves, but that involves work on our side. I will try one last time to find a way in the popper and tippy docs to disable this and update it here, but this is what I have tried so far.

**Comment by mayank99** [comment]
Closing this as we want to get rid of tippy.js completely.

**Comment by rohan-kadkol** [comment]
> Closing this as we want to get rid of tippy.js completely.

Until we do this, the itwinjs-core team have PR [#4717](https://github.com/iTwin/itwinjs-core/pull/4717) to change the way they hide the dialog backdrop. [L37-39](https://github.com/iTwin/itwinjs-core/pull/4717/files#diff-d2183256883819883007cc11f39bec0c2236a6bc16fedd4e3311b4a9c4ae1caeL37-R39) fixes this issue.
