### ISSUE TITLE
Visual testing of React components

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI-react#81]
Lets research Storybook add-ons for this one.

**Comment by wKich** [comment]
@mayank99, Hi 👋  Author of Creevey is here. Thank you for using my tool. If you have any questions or feature requests, feel free to ask. BTW I recommend to setup git LFS for screenshots. It helps keep git history small, by storing image hash in commits and upload images to Github LFS

**Comment by mayank99** [comment]
Hi @wKich, thanks for reaching out and for the suggestion. We might migrate to Git LFS in the future (it's only ~2.5MB currently).

Creevey is working pretty well for our needs so far. We did find a few issues:
- **0.7.30 did not compile** for us (`Cannot find module '@storybook/builder-webpack4'`).
- Running tests repeatedly makes the report folder grow in size over time, with no way to clean old images.
- 0.7.29 does not use same webpack from storybook (our storybook is on webpack4 and we also have webpack5 in devdeps).
- Running `yarn creevey --update` is not reliable (should only change for failed tests or remove unneeded images).
- Selenium's `mouseMove` does not work (had to use `move` as workaround).
- Random test failures (had to increase maxRetries to pass reliably).

All of those, except maybe the first one, we can definitely live with, so no big deal.

One thing we were wondering is what's a safe `limit` for parallel test runs. We have just set it to 5 for now, and it still seems a bit slow in CI.

**Comment by wKich** [comment]
Thanks for the reply. The feedback is very important for me.

Here is a nice [migration guide](https://support.atlassian.com/bitbucket-cloud/docs/use-bfg-to-migrate-a-repo-to-git-lfs/) to Git LFS. Bear in mind you have to rewrite history and push force your main branch. So it less painful to do it early :)

- Hm... interesting, I'll take a look. I changed resolving logic for one monorepo project, but it looks like doesn't work for you.
- Yeah, think about it as a history of all previous runs. I understand that could be a problem over a significant amount of time, but don't know what is the best way to deal with it instead of manually remove it. Maybe remove it before each start.
- I don't see webpack@5 in devdeps. It looks like you downgrade storybook from 6.2. I made a fix for it in 0.7.30, but don't sure if it related to you
- Sounds reasonable. 👍 
- `moseMove` is a deprecated API and exists only in selenium@3. Creevey uses selenium@4. The issue is the old methods still exist in type definitions. [There is an actual API](https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/input_exports_Actions.html)
- I know one chrome related issue with borders, where corners are captured with a different color each time, just a few pixels, very annoying. I don't know source of that problem. I think I should add support alternative webdrivers, like puppeteer or playwright.

The number of parallel test runs is dependent on CPU and available memory. I don't know that the best value for github action agents. According to [specs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) it seems you can't get any performance benefits with concurrency greater than 4. But 5 should be also fine, I guess.
