### ISSUE TITLE
Table: add ability to customize react table

### ISSUE THREAD

**Issue by DziugasRam** [iTwin/iTwinUI-react#818]
#### Feature
Ability to customize react table with react table plugin hooks and access to the table instance.

#### Examples
In my PR - [feat(Table): Add useGlobalFilter](https://github.com/iTwin/iTwinUI-react/pull/810), I added a default global filtering plugin hook, which is likely a feature that not many use cases need, but there is no way for me to only add it in my own project without adding it for everyone here, because it requires modifications for the `useTable` hook call and access to an additional callback from the table instance.

Maybe allowing consumers to call the `useTable` hook themselves and then passing in the table instance as a prop to the iTwin-UI table would be a good way to allow full access to the logical side of the table if uncommon table modifications are needed?

**Comment by bentleyvk** [comment]
Hi Dziugas,

it usually is that if one person needs some feature there will definitely be another that needs it too. So e.g. by adding global filtering we prevent code duplication across different projects because if I remember correctly there were already several people asking about global filtering. But if there will be a need for a very uncommon feature, we might consider it.
And remember:
![spider-man-uncle-ben](https://user-images.githubusercontent.com/36186912/188652024-ddb67601-2a57-4244-ba04-d402ff34f4bc.gif)
