### ISSUE TITLE
If we have more than one item with same label in the ComboBox then search doesn't works

### ISSUE THREAD

**Issue by mshafiqmk** [iTwin/iTwinUI-react#863]
#### Describe the bug (actual behavior)

If we have more than one item with same label in the combo box then search doesn't works 
#### Reproduction
Link to a minimal repro: 
https://codesandbox.io/s/itwinui-react-minimal-example-forked-vm46v8?file=/src/App.tsx

##### Steps to reproduce
1. type default and clear it , type it again , first will appear as result , even though first and default are two different strings
1. If we keep on searching for default or some other string then on each search first will be added to the list .

#### Additional information

![7B7EE953-CAF2-40BE-94E3-3DEE10F38789](https://user-images.githubusercontent.com/21343093/194553547-d05b6503-8fde-43d6-9783-7b5b2708b199.GIF)

**Comment by mayank99** [comment]
Hi @mshafiqmk, thanks for the issue.

First off, I would question Is there a valid reason for having two items with the same label? It sounds like a confusing user experience.

Now from the technical part: we use the label as a `key` for our menu items, and keys are meant to be unique. But we also default to using the `id` in the key if provided, since ids are meant to be globally unique (and we can't use `value` because it's not guaranteed to be serializable). So you can pass an id to your options using [`useId`](https://beta.reactjs.org/apis/react/useId) or [`nanoid`](https://github.com/ai/nanoid).

Hope that helps.

**Comment by mshafiqmk** [comment]
Hi @mayank99, thanks for responding to the issue.

We have a use case where multiple items could have the same label but different values and we are already using the kendo component in our old app which supports this use case for which we want to use this component.

This is how it looks like in the kendo component and there is no issue with having multiple labels with the same text.

![CB2B6CD4-F1C3-4198-87D8-25B66E4CA10D](https://user-images.githubusercontent.com/21343093/195076044-29baa8f9-93e7-4315-81e0-8f956f71b45c.GIF)
