### ISSUE TITLE
Update codesandboxes with the latest changes

### ISSUE THREAD

**Issue by gretanausedaite** [iTwin/iTwinUI-react#948]
Update code sandbox examples with react v2
<img width="1544" alt="image" src="https://user-images.githubusercontent.com/83585998/203056117-7ab62b64-0b4d-4c48-bfc9-e89cee0b2950.png">

**Comment by mayank99** [comment]
I think @veekeys owns the codesandbox we currently use. Thinking from a maintainability perspective, we should probably have the code for the sandbox be _inside_ our repo (kinda like how we want to add examples in #929). Codesandbox and Stackblitz both support using github as a source.

Currently if you try to use the vite playground as a source, it fails because it relies on private deps (`configs`) in the monorepo. We shouldn't really rely on that tsconfig because it's meant for our package, not for playgrounds or examples (which should be standalone imo).
- https://stackblitz.com/github/iTwin/iTwinUI-react/tree/main/apps/playground
- https://codesandbox.io/s/github/iTwin/iTwinUI-react/tree/main/apps/playground

Once we do that, we would just need to update the links in our README and issue templates.

**Comment by veekeys** [comment]
As for now, I fixed the compilation issue.
Check up if need to change something else.

**Comment by veekeys** [comment]
Updated.
I guess you can close this and update other issue with support of playground complication in cloud.
